version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hurumap
      MYSQL_USER: hurumap
      MYSQL_PASSWORD: hurumap
      MYSQL_ROOT_PASSWORD: hurumap
  es:
    build: ./docker/elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      
  web:
    image: wordpress
    depends_on:
      - db
      - es
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./.htaccess:/var/www/html/.htaccess
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: hurumap
      WORDPRESS_DB_USER: hurumap
      WORDPRESS_DB_PASSWORD: hurumap
      ELASTICSEARCH_INDEX: hurumap
      ELASTICSEARCH_HOST: http://es:9200
volumes:
  db-data:
